import time
timestamp = time.strftime("%H:%M:%S:%MS")
print(timestamp)
timestamp = int(time.strftime("%H"))
print(timestamp)
timestamp = time.strftime("%M")
print(timestamp)
timestamp = time.strftime("%S")
print(timestamp)
timestamp = time.strftime("%MS")
print(timestamp)
